<?php

namespace ExchangeRateBundle\Repository;

/**
 * RateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RateRepository extends \Doctrine\ORM\EntityRepository
{
    public function getMinimum()
    {
        return $this->createQueryBuilder('u')
            ->select('e.id, MIN(e.usdtry) as usdtry,MIN(e.eurtry) as eurtry,' .
                'MIN(e.gbptry) as gbptry,MAX(e.updatedAt) as updatedAt')
            ->from('ExchangeRateBundle:Rate', 'e')
            ->getQuery()
            ->getSingleResult();
    }
}
